### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by rawnly** [raymanfx/eye-rs#6]
Hello! Cool project! But I'm not able to run any of your examples / readme. 
Platform: macos 13.0

![CleanShot 2023-01-17 at 22 14 06@2x](https://user-images.githubusercontent.com/16429579/213013696-18bd93d0-abe3-460d-8244-21e8dd2e04d7.png)

**Comment by raymanfx** [comment]
Hi, it looks like you might be using an old checkout of the source?
The particular line referenced by your error message is here: https://github.com/raymanfx/eye-rs/blob/master/eye-hal/src/platform/mod.rs#L49 but points to something completely different. The `default` method does not exist anymore for the `Context` type in the latest master branch.

Let me know whether that makes sense. I am building on Ventura 13.1 myself.

**Comment by rawnly** [comment]
Yeah I saw the source code. But the only thing I did was `cargo add eye_halt` :/ I'll try manually

**Comment by rawnly** [comment]
The version is the right one... 
Here's my`Cargo.toml`
```toml
[package]
name = "my-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eye-hal = "0.1.0"

```
